FROM ros:iron-ros-base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ros-iron-usb-cam \
        ros-iron-image-transport-plugins \
        v4l-utils && \
    rm -rf /var/lib/apt/lists/*

ENV ROS_DOMAIN_ID=0 \
    CAM_DEV=/dev/video1 \
    IMAGE_WIDTH=640 \
    IMAGE_HEIGHT=480 \
    FRAME_RATE=15 \
    PIXEL_FORMAT=mjpeg \
    IO_METHOD=mmap

COPY docker/entrypoint-usb-camera.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
