FROM ros:iron-ros-base
RUN apt-get update && apt-get install -y --no-install-recommends \
      ros-iron-rmw-cyclonedds-cpp \
      ros-iron-v4l2-camera \
    && rm -rf /var/lib/apt/lists/*
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
CMD ["bash","-lc","source /opt/ros/iron/setup.bash && ros2 run v4l2_camera v4l2_camera_node"]
