services:
  video-dashboard:
    image: nginx:1.29-alpine
    container_name: video-dashboard
    restart: unless-stopped
    ports: ["8081:80"]
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:rw
      - ../site:/usr/share/nginx/html:ro
    depends_on:
      - netstatus
      - web-video-server
    networks:
      - robotnet

  netstatus:
    build:
      context: ../services/netstatus
    container_name: netstatus
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:5000/status', timeout=3).getcode()==200 else 1)\""]
      interval: 20s
      timeout: 5s
      retries: 6
      start_period: 25s
    networks:
      - robotnet

  web-video-server:
    image: ros:iron-ros-core  # (or your existing image)
    container_name: web-video-server
    # ... your existing config ...
    networks:
      - robotnet

networks:
  robotnet:
    driver: bridge
