services:
  roboclaw_driver:
    image: python:3.11-slim
    devices:
      - "/dev/roboclaw:/dev/roboclaw"
    environment:
      ROBOCLAW_PORT: "/dev/roboclaw"
      ROBOCLAW_ADDR: "128"
      ROBOCLAW_BAUD: "115200"
    volumes:
      - ../roboclaw_probe.py:/opt/roboclaw_probe.py:ro
    command: >
      bash -lc "pip install --no-cache-dir pyserial >/dev/null;
                while true; do python /opt/roboclaw_probe.py || true; sleep 2; done"
    restart: unless-stopped
