services:
  usb-camera:
    # make sure the device is present inside the container
    devices:
      - /dev/video0:/dev/video0
    # override the confusing base env
    environment:
      PIXEL_FORMAT: yuyv
    command:
      - bash
      - -lc
      - |
        set -euo pipefail
        # ensure v4l2-ctl exists
        apt-get update && apt-get install -y --no-install-recommends v4l-utils \
          && rm -rf /var/lib/apt/lists/*
        # force the camera itself into YUYV @ 640x480/15fps
        v4l2-ctl -d /dev/video0 \
          --set-fmt-video=width=640,height=480,pixelformat=YUYV \
          --set-parm=15 || true
        # (optional) show what the device reports now
        v4l2-ctl -d /dev/video0 --get-fmt-video --get-parm || true

        source /opt/ros/iron/setup.bash
        echo "[usb-camera] Launching usb_cam with pixel_format=yuyv"
        exec ros2 run usb_cam usb_cam_node_exe --ros-args \
          -p video_device:=/dev/video0 \
          -p framerate:=15.0 \
          -p image_width:=640 \
          -p image_height:=480 \
          -p io_method:=mmap \
          -p pixel_format:=yuyv \
          -r __node:=usb_cam
