services:
  usb-camera:
    devices:
      - /dev/video0:/dev/video0
    command:
      - bash
      - -lc
      - |
        set -eo pipefail
        source /opt/ros/iron/setup.bash
        exec ros2 run usb_cam usb_cam_node_exe --ros-args \
          -p video_device:=/dev/video0 \
          -p pixel_format:=yuyv \
          -p io_method:=mmap \
          -p framerate:=15.0 \
          -p image_width:=640 \
          -p image_height:=480 \
          -p camera_name:=c920 \
          -r __node:=usb_cam
