services:
  netstatus:
    build:
      context: ${PROJECT_ROOT}/services/netstatus
    image: robot-netstatus
    restart: unless-stopped
    expose:
      - "5000"
    networks:
      - robot-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request as u; u.urlopen('http://127.0.0.1:5000/healthz', timeout=2).read()"]
      interval: 30s
      timeout: 3s
      retries: 3

  video-dashboard:
    image: nginx:stable
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT:-8081}:80"
    networks:
      - robot-net
    volumes:
      - ${PROJECT_ROOT}/site:/usr/share/nginx/html:ro
      - ${PROJECT_ROOT}/site/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      web-video-server:
        condition: service_healthy
      #netstatus:
      #  condition: service_healthy

networks:
  robot-net: {}
